version: '3'
services:
  bot_db:
    image: postgres:15
    ports:
      - 32704:5432 # 32704 внешний порт для подключения к бд
    volumes:
      - /var/lib/user_bot:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bot_data
    networks:
      - botnetwork3